/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilya_kashkarev' at '11/29/16 10:06 PM' with Gradle 2.6
 *
 * @author ilya_kashkarev, @date 11/29/16 10:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
